# Fedora builds are implemented but are disabled until we decide we
# need them; Travis limits our number of concurrent jobs so we don't
# want more than are necessary.
# The Fedora docker images are "fedora:26" and "fedora:27"

# Also, the following gram tests failed for all fedora versions:
#   nonblocking-register-test.pl, register-callback-test.pl, register-test.pl
arch:
  # Disabled for now
  #- amd64
  # Handled via partner queue, uncharged
  - ppc64le
  #- arm64
jobs:
  include:

    - &run_tests
      # Template; subsequent uses modify 'env'
      env:
        - IMAGE=centos:centos7 TASK=tests COMPONENTS=udt,myproxy,ssh
      stage: test
      sudo: required
      services:
        - docker

      before_install:
        - sudo apt-get update
        - sleep 5
        - sudo docker pull ${IMAGE}

      script:
      - travis-ci/setup_tasks.sh
    - <<: *run_tests
      env:
        - IMAGE=centos:centos7 TASK=tests COMPONENTS=gram5
