name: Run Travis CI

on:
  push:
  pull_request:
#     tags:
#       - v[0-9]+.[0-9]+.[0-9]+
#       - v[0-9]+.[0-9]+.[0-9]+.[0-9]+
      
jobs:
  run-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['centos:centos7']
        task: ['tests']
        components: ['udt,myproxy,ssh', 'gram5']
    steps:
      - uses: actions/checkout@v2
    
      - name: setup tasks
        env:
          IMAGE: ${{ matrix.image }} 
          TASK: ${{ matrix.task }} 
          COMPONENTS: ${{ matrix.components }} 
        run: travis-ci/setup_tasks.sh
        
      - name: setup tasks with srpms
        env:
          IMAGE: centos:centos7
          TASK: srpms
        run: travis-ci/setup_tasks.sh
      
      # SSH key recipe from https://www.webfactory.de/blog/use-ssh-key-for-private-repositories-in-github-actions
      - name: Establish ssh
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          ssh-agent -a "$SSH_AUTH_SOCK" > /dev/null
          ssh-add - <<< "${{ secrets.ID_GCTUPLOADER }}"
